---
name: 'OIDC Example'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  oidc-example:
    name: 'OIDC'
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Zentral
        id: auth
        uses: zentralopensource/zentral-oidc-auth@main
        with:
          ztl-fqdn: zaio.zentral.dev # required
          ztl-oidc-api-token-issuer-id: ${{ vars.ZTL_OIDC_API_TOKEN_ISSUER_ID }} # required
          ztl-api-token-name: "Token for my Github action" # optional
          ztl-api-token-validity: 1200 # optional
          ztl-oidc-debug: 1 # optional

      - name: Use the token
        run: |
          echo "ZENTRAL_API_TOKEN (from previous step): $STEP_API_TOKEN"
          echo "ZENTRAL_API_USERNAME (from previous step): $STEP_API_USERNAME"
          echo "ZENTRAL_API_USEREMAIL (from previous step): $STEP_API_USEREMAIL"
          echo "ZTL_API_TOKEN (from ENV): $ZTL_API_TOKEN" # will be set directly from zentral-oidc-auth
          echo "ZTL_USERNAME (from ENV): $ZTL_USERNAME" # will be set directly from zentral-oidc-auth
          echo "ZTL_API_USERNAME (from ENV): $ZTL_API_USERNAME" # will be set directly from zentral-oidc-auth
          echo "ZTL_API_USEREMAIL (from ENV): $ZTL_API_USEREMAIL" # will be set directly from zentral-oidc-auth
        env:
          STEP_API_TOKEN: ${{ steps.auth.outputs.ztl-api-token }}
          STEP_API_USERNAME: ${{ steps.auth.outputs.ztl-api-username }}
          STEP_API_USEREMAIL: ${{ steps.auth.outputs.ztl-api-useremail }}